#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged
bun lint-staged

# Run type check
echo "🔍 Running type check..."
bun typecheck

# Run tests for changed files
echo "🧪 Running tests..."
bun test --passWithNoTests --findRelatedTests
